---
title: "2025 DPI Superintendent Primary results in Milwaukee"
format: 
  html:
    embed-resources: true
editor: visual
execute: 
  echo: false
  warning: false
  message: false
---

```{r setup}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)

library(tidyverse)
library(sf)
library(RColorBrewer)
library(colorspace)
library(leaflet)
library(mapboxapi)
library(mapboxer)
library(glue)
library(scales)

cols <- c(
  "#1F77B4",
  "#FF7F0E",
  "#2CA02C"
)

d <- read_csv("data/votes.csv") |> 
  mutate(ward = str_remove(Ward, "City of Milwaukee Ward ") |> 
           str_trim()) |> 
  pivot_longer(cols = c(3:6), names_to = "candidate", values_to = "votes") |> 
  select(-c(id, Ward)) |> 
  group_by(ward) |> 
  mutate(perc = votes / sum(votes),
         col = case_when(
           candidate == "Jeff Wright" ~ cols[1],
           candidate == "Brittany Kinser" ~ cols[2],
           candidate == "Jill Underly" ~ cols[3]
         ))

w <- st_read("data/ward/ward.shp", quiet = TRUE) |> 
  transmute(ward = WARD,
            geometry)


all <- left_join(w, d) |>
  st_transform(crs = 4326)

wins <- all |> 
  as_tibble() |> 
  group_by(ward) |> 
  filter(perc == max(perc)) |> 
  select(ward, 
         winner = candidate,
         perc,
         col)

wider <- all |> 
  select(-c(votes, col)) |> 
  pivot_wider(names_from = candidate, values_from = perc) |> 
  left_join(wins)

wider_n <- all |> 
  select(-c(perc, col)) |> 
  pivot_wider(names_from = candidate, values_from = votes) |> 
  left_join(wins)
```

## City of Milwaukee vote margin

```{r citywide}
overall <- read_csv("data/votes.csv") |> 
  filter(str_detect(Ward, "City of Milwaukee")) |> 
  pivot_longer(cols = c(3:6), names_to = "candidate", values_to = "votes") |> 
  group_by(candidate) |> 
  summarise(total = sum(votes)) |> 
  mutate(perc = total / sum(total))

overall |> 
  filter(candidate != "write-in:") |> 
  ggplot(aes(candidate, perc, fill = candidate)) +
  geom_col(width = .75) +
  geom_text(aes(label = label_percent(.1)(perc)),
            fontface = "bold", size = 8, nudge_y = .02) +
  scale_y_continuous(labels = label_percent(),
                     breaks = c(0, .25, .5)) +
  scale_fill_manual(values = cols[c(2,1,3)]) +
  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(face = "bold", size = 14)) +
  labs(y = "", x = "")
```
## Ward Winners

The map below shows the results of the spring primary for DPI Superintendent in the city of Milwaukee. Boundaries represent wards.

```{r map}
#| fig-height: 11

leaflet(wider) |>
  addMapboxTiles(style_id = "light-v11",
                 username = "mapbox",
                 scaling_factor = "0.5x") |>
  addPolygons(weight = 2,
              fillColor = wider$col, fillOpacity = .9,
              color = "white",
              popup = glue("<strong>Ward {wider$ward}</strong>",
                           "<br>Wright: {label_percent(.1)(wider$`Jeff Wright`)}",
                           "<br>Kinser: {label_percent(.1)(wider$`Brittany Kinser`)}",
                           "<br>Underly: {label_percent(.1)(wider$`Jill Underly`)}"),
              popupOptions = popupOptions(autoPan = TRUE),
              highlight = highlightOptions(color = "black", fillColor = "white",
                                           fillOpacity = .25, bringToFront = TRUE)) |> 
  addLegend(colors = cols, opacity = 1, 
            labels = c("Wright", "Kinser", "Underly"), 
            position = "topright")

```


## Kinser Margin

```{r kinser_map}
#| fig-height: 11

pa <- sequential_hcl(5, "YlOrRd")
pal <- colorBin(rev(pa), domain = c(0, 1))

leaflet(wider) |>
  addMapboxTiles(style_id = "light-v11",
                 username = "mapbox",
                 scaling_factor = "0.5x") |>
  addPolygons(weight = 2,
              fillColor = ~pal(`Brittany Kinser`), 
              fillOpacity = .9, 
              color = "white",
              popup = glue("<strong>Ward {wider$ward}</strong>",
                           "<br>Wright: {label_percent(.1)(wider$`Jeff Wright`)}",
                           "<br>Kinser: {label_percent(.1)(wider$`Brittany Kinser`)}",
                           "<br>Underly: {label_percent(.1)(wider$`Jill Underly`)}"),
              popupOptions = popupOptions(autoPan = TRUE),
              highlight = highlightOptions(color = "black", fillColor = "white",
                                           fillOpacity = .25, bringToFront = TRUE)) |> 
  addLegend(pal = pal, values = ~n, position = "topright", title = "Kinser Margin")

```

## Underly Margin

```{r underly_margin}
#| fig-height: 11

pa <- sequential_hcl(5, "YlOrRd")
pal <- colorBin(rev(pa), domain = c(0, 1))


leaflet(wider) |>
  addMapboxTiles(style_id = "light-v11",
                 username = "mapbox",
                 scaling_factor = "0.5x") |>
  addPolygons(weight = 2,
              fillColor = ~pal(`Jill Underly`), 
              fillOpacity = .9, 
              color = "white",
              popup = glue("<strong>Ward {wider$ward}</strong>",
                           "<br>Wright: {label_percent(.1)(wider$`Jeff Wright`)}",
                           "<br>Kinser: {label_percent(.1)(wider$`Brittany Kinser`)}",
                           "<br>Underly: {label_percent(.1)(wider$`Jill Underly`)}"),
              popupOptions = popupOptions(autoPan = TRUE),
              highlight = highlightOptions(color = "black", fillColor = "white",
                                           fillOpacity = .25, bringToFront = TRUE)) |> 
  addLegend(pal = pal, values = ~n, position = "topright", title = "Underly Margin")

```

## Underly Vote Count

```{r underly_count}
#| fig-height: 11

pa <- sequential_hcl(5, "YlOrRd")
pal <- colorBin(rev(pa), domain = c(0, 400))


leaflet(wider_n) |>
  addMapboxTiles(style_id = "light-v11",
                 username = "mapbox",
                 scaling_factor = "0.5x") |>
  addPolygons(weight = 2,
              fillColor = ~pal(`Jill Underly`), 
              fillOpacity = .9, 
              color = "white",
              popup = glue("<strong>Ward {wider_n$ward}</strong>",
                           "<br>Wright: {wider_n$`Jeff Wright`}",
                           "<br>Kinser: {wider_n$`Brittany Kinser`}",
                           "<br>Underly: {wider_n$`Jill Underly`}"),
              popupOptions = popupOptions(autoPan = TRUE),
              highlight = highlightOptions(color = "black", fillColor = "white",
                                           fillOpacity = .25, bringToFront = TRUE)) |> 
  addLegend(pal = pal, values = ~n, position = "topright", title = "Underly Margin")

```